server.port: 8081

service:
  jwtAlgorithmKey: sampleJwtAlgorithmKey
  registeredSecretKeys: serviceB-SecretKey-Provided-By-ServiceA
  numRecordsOnPage: 100

spring:
  application.name: "MetricsAPI"
  datasource:
    url: jdbc:postgresql://localhost:5432/metrics
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE



